//! Compile-time validating proc-macros for `warp_i18n` (D17).
//!
//! - `t!("literal-key")`            → validated literal lookup
//! - `t!("literal-key", n = expr)`  → validated literal + Fluent args
//!
//! The set of valid keys is generated by `build.rs` from `bundles/en/*.ftl` of the
//! sibling `warp_i18n` crate; missing keys produce `compile_error!` at expansion time.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::parse::{Parse, ParseStream};
use syn::{Expr, Ident, LitStr, Result as SynResult, Token, parse_macro_input};

include!(concat!(env!("OUT_DIR"), "/keys.rs"));

struct TInput {
    key: LitStr,
    args: Vec<(Ident, Expr)>,
}

impl Parse for TInput {
    fn parse(input: ParseStream) -> SynResult<Self> {
        let key: LitStr = input.parse()?;
        let mut args = Vec::new();
        while !input.is_empty() {
            input.parse::<Token![,]>()?;
            if input.is_empty() {
                break;
            }
            let name: Ident = input.parse()?;
            input.parse::<Token![=]>()?;
            let value: Expr = input.parse()?;
            args.push((name, value));
        }
        Ok(Self { key, args })
    }
}

#[proc_macro]
pub fn t(input: TokenStream) -> TokenStream {
    let TInput { key, args } = parse_macro_input!(input as TInput);
    let key_str = key.value();

    if !EN_KEY_INDEX.contains(&key_str.as_str()) && !EN_KEY_INDEX.is_empty() {
        let msg = format!(
            "warp_i18n: key `{key_str}` not found in en bundle (crates/warp_i18n/bundles/en/*.ftl). Add it before referencing."
        );
        return quote! { compile_error!(#msg) }.into();
    }

    let body: TokenStream2 = if args.is_empty() {
        quote! {
            ::warp_i18n::render(#key, ::core::option::Option::None)
        }
    } else {
        let setters = args.iter().map(|(name, value)| {
            let name_str = name.to_string();
            quote! {
                __args.set(#name_str, ::warp_i18n::FluentValue::from(#value));
            }
        });
        quote! {
            {
                let mut __args = ::warp_i18n::FluentArgs::new();
                #(#setters)*
                ::warp_i18n::render(#key, ::core::option::Option::Some(&__args))
            }
        }
    };
    body.into()
}
